about.stab<-function(){
cat("\n\n")
cat("............................................................................\n")
cat(" This package is designed to analyze drug stability data. The ICH Guideline \n") 
cat(" 'Q1E Evaluation for Stability Data' is followed to propose a retest period \n")
cat(" or shelf life.  This guideline describes when and how extrapolation should \n")
cat(" be considered when proposing a retest period for a drug substance or a     \n")
cat(" shelf life for a drug product that extends beyond the period covered by    \n")
cat(" available data from the stability under the long-term storage condition.   \n")
cat("                                                                            \n")
cat(" The following steps will be performed:                                     \n")
cat(" ->1: Decision Tree for Data Evaluation (batch data poolability)            \n")
cat(" ->2: Statistical Approaches to Stability Data Analysis                     \n")
cat("    ->2-1: Data Analysis for a Single Batch; or                             \n")
cat("    ->2-2: Data Analysis for multiple Batches                               \n")
cat("............................................................................\n")
cat("\n\n")
cat(" type 'go()' to get started.\n\n")
}